version: "3.9"

services:
  myDB:
    image: postgres
    container_name: not-today-db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=not-today-db
    volumes:
      - ./postgres:/var/lib/postgresql/data
